---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # cert-manager.io/clusterissuer: "letsencrypt-vc2"
    # cert-manager.io/acme-challenge-type: http01
    networking.gke.io/pre-shared-certs: mcrt-671a30bc-b06c-430e-9ab6-2090c0f9a375
  name: vc2-ingress
  namespace: team-b
spec:
  # tls:
  # - hosts:
  #   - vc2.goinit.net
  #   secretName: letsencrypt-vc2-secret
  ingressClassName: nginx
  rules:
  - host: vc2.goinit.net
    http:
      paths:
      - backend:
          service:
            name: vc2
            port: 
              number: 443
        path: /
        pathType: ImplementationSpecific